name: json_component
description: "Flutter dynamic component from json"
version: 0.0.2
homepage:

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
flutter:
  plugin:
    platforms:
      android:
        package: id.herisetiawan.json_component
        pluginClass: JsonComponentPlugin
      ios:
        pluginClass: JsonComponentPlugin
      linux:
        pluginClass: JsonComponentPlugin
      macos:
        pluginClass: JsonComponentPlugin
      windows:
        pluginClass: JsonComponentPluginCApi
